from librosa import midi_to_hz, note_to_midi

RANDOM_STATE = 42 # the answer to life, the universe and everything

HOP_LENGTH = 512
N_FFT = 1024
WIN_LENGTH = None
SAMPLE_RATE = 44100

STEP_FRAME = 5
STEP_TIME = STEP_FRAME * (HOP_LENGTH/SAMPLE_RATE)
PICKING_FRAME_SIZE = 210
PICKING_FRAME_TIME = PICKING_FRAME_SIZE * STEP_TIME
PICKING_FRAME_STEP = int(PICKING_FRAME_SIZE/2)


N_MELS = 88
N_CLASS = 88
ONSET_TIME_THRESHOLD = 0.06


MIDI_START = note_to_midi('C1')
MIDI_END = MIDI_START + 88
PRE_MIDI_START = MIDI_START - 1

F_MIN = midi_to_hz(MIDI_START)