from librosa import midi_to_hz, note_to_midi

RANDOM_STATE = 42 # the answer to life, the universe and everything

HOP_LENGTH = 512
N_FFT = 1024
WIN_LENGTH = None
SAMPLE_RATE = 44100

ANALYSIS_FRAME_SIZE = 5
# ANALYSIS_FRAME_SIZE = 5
ANALYSIS_FRAME_TIME = ANALYSIS_FRAME_SIZE * (HOP_LENGTH/SAMPLE_RATE)
PATCH_SIZE = 210
PATCH_TIME = PATCH_SIZE * ANALYSIS_FRAME_TIME
PATCH_STEP = int(PATCH_SIZE/2)


N_MELS = 88
N_CLASS = 89 # 1 non-melody class + 88 pitch classes
ONSET_TIME_THRESHOLD = 0.06

# 88 keyboards, A0->C8
MIDI_START = note_to_midi('A0')
MIDI_END = MIDI_START + 88
PRE_MIDI_START = MIDI_START - 1

F_MIN = midi_to_hz(MIDI_START)
